services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      GROQ_API_KEY: ${GROQ_API_KEY}

    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  postgres_data:
   
