-- MSSQL / Azure SQL import flow for WKT CSV files generated by:
--   export_geojson_to_wkt_csv.py
--
-- Recommended flow:
-- 1. Run the Python script to generate CSV files in ./output
-- 2. Import the CSV files into the staging tables below
--    - Azure Data Studio Import Wizard, or
--    - bcp / SqlBulkCopy, or
--    - BULK INSERT from Azure Blob storage if your environment supports it
-- 3. Move data from staging into final tables and convert WKT to geometry

IF OBJECT_ID('dbo.vic_lga_boundaries_stage', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.vic_lga_boundaries_stage (
        abb_name NVARCHAR(255) NULL,
        dt_create DATE NULL,
        lga_name NVARCHAR(255) NOT NULL,
        lga_pid NVARCHAR(100) NOT NULL,
        lg_ply_pid NVARCHAR(100) NOT NULL,
        state NVARCHAR(10) NOT NULL,
        geometry_wkt NVARCHAR(MAX) NOT NULL,
        source_file NVARCHAR(255) NULL
    );
END;
GO

IF OBJECT_ID('dbo.vic_locality_boundaries_stage', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.vic_locality_boundaries_stage (
        dt_create DATE NULL,
        lc_ply_pid NVARCHAR(100) NOT NULL,
        loc_class NVARCHAR(255) NULL,
        loc_name NVARCHAR(255) NOT NULL,
        loc_pid NVARCHAR(100) NOT NULL,
        state NVARCHAR(10) NOT NULL,
        geometry_wkt NVARCHAR(MAX) NOT NULL,
        source_file NVARCHAR(255) NULL
    );
END;
GO

IF OBJECT_ID('dbo.vic_lga_boundaries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.vic_lga_boundaries (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        abb_name NVARCHAR(255) NULL,
        dt_create DATE NULL,
        lga_name NVARCHAR(255) NOT NULL,
        lga_pid NVARCHAR(100) NOT NULL,
        lg_ply_pid NVARCHAR(100) NOT NULL,
        state NVARCHAR(10) NOT NULL,
        geom geometry NOT NULL,
        source_file NVARCHAR(255) NULL
    );
END;
GO

IF OBJECT_ID('dbo.vic_locality_boundaries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.vic_locality_boundaries (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        dt_create DATE NULL,
        lc_ply_pid NVARCHAR(100) NOT NULL,
        loc_class NVARCHAR(255) NULL,
        loc_name NVARCHAR(255) NOT NULL,
        loc_pid NVARCHAR(100) NOT NULL,
        state NVARCHAR(10) NOT NULL,
        geom geometry NOT NULL,
        source_file NVARCHAR(255) NULL
    );
END;
GO

